"""A guidance document as a structured collection of Markdown.

The document is a wrapper around raw Markdown, not a representation that has to be
converted into it: each section carries its own finished Markdown, and the whole
document is the ordered concatenation of its sections.

The content is a *template* with exactly one late-bound hole - where the images
live. Images are written into the Markdown by their generated name alone, and the
caller supplies the prefix at render time, so the same parsed document can be
rendered for S3, for a local directory, or for anywhere else.

Hierarchy is carried by each section's parent link, and a section's number is
*derived* from that link rather than stored, so no stored number can disagree with
the structure.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Image:
    """An image extracted from a document.

    `name` is the bare generated filename as it appears in the section's Markdown,
    before any prefix is applied.
    """

    name: str
    data: bytes
    content_type: str


@dataclass
class MarkdownSection:
    """One numbered section of a document, holding its own Markdown.

    `ordinal` is the section's 1-based position among its siblings. Together with
    `parent` it is the whole of the numbering: `number` and `depth` are computed by
    walking up the parent chain.
    """

    heading: str
    ordinal: int = 1
    parent: MarkdownSection | None = None
    content: str = ""
    images: list[Image] = field(default_factory=list)

    @property
    def depth(self) -> int:
        """How deep this section sits, counting top-level sections as 1."""
        return 1 if self.parent is None else self.parent.depth + 1

    @property
    def number(self) -> str:
        """The derived section number, e.g. "3.1.2"."""
        if self.parent is None:
            return str(self.ordinal)
        return f"{self.parent.number}.{self.ordinal}"

    def markdown(self, image_prefix: str = "") -> str:
        """This section's own Markdown: its heading and content, not its children."""
        hashes = "#" * (self.depth + 1)
        lines = [f"{hashes} {self.number} {self.heading}", ""]

        content = self._resolved_content(image_prefix)
        if content:
            lines.extend((content, ""))

        return "\n".join(lines)

    def _resolved_content(self, image_prefix: str) -> str:
        """Fill the template's one hole: where this section's images live.

        Only a link target is rewritten, never prose. The names being rewritten are
        generated by the parser (`3.1_img_2.png`), so they cannot collide with
        anything the document itself says.
        """
        if not image_prefix:
            return self.content

        content = self.content
        for image in self.images:
            content = content.replace(
                f"]({image.name})", f"]({image_prefix}{image.name})"
            )
        return content


@dataclass
class MarkdownDocument:
    """A parsed guidance document: a title and its sections in document order."""

    title: str = ""
    sections: list[MarkdownSection] = field(default_factory=list)

    @property
    def images(self) -> list[Image]:
        """Every image in the document, in section order."""
        return [image for section in self.sections for image in section.images]

    def markdown(self, image_prefix: str = "") -> str:
        """The whole document: its title followed by every section in order."""
        parts = [f"# {self.title}", ""]
        parts.extend(section.markdown(image_prefix) for section in self.sections)
        return "\n".join(parts)
