"""A guidance document as a structured collection of Markdown.

The document is a wrapper around raw Markdown, not a representation that has to be
converted into it: each section carries its own finished Markdown, and the whole
document is the ordered concatenation of its sections.

The content is a *template* with two late-bound holes. Images are written into the
Markdown by their generated name alone, and the caller supplies the prefix at render
time, so the same parsed document can be rendered for S3, for a local directory, or
for anywhere else. Cross-references are written as the name of the Word bookmark
they point at, which means nothing to a renderer, and are resolved to the section
that bookmark marks - only the document as a whole knows which section that is.

Hierarchy is carried by each section's parent link, and a section's number is
*derived* from that link rather than stored, so no stored number can disagree with
the structure.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class Image:
    """An image extracted from a document.

    `name` is the bare generated filename as it appears in the section's Markdown,
    before any prefix is applied.
    """

    name: str
    data: bytes
    content_type: str


@dataclass
class MarkdownSection:
    """One numbered section of a document, holding its own Markdown.

    `ordinal` is the section's 1-based position among its siblings. Together with
    `parent` it is the whole of the numbering: `number` and `depth` are computed by
    walking up the parent chain.
    """

    heading: str
    ordinal: int = 1
    parent: MarkdownSection | None = None
    content: str = ""
    images: list[Image] = field(default_factory=list)

    @property
    def depth(self) -> int:
        """How deep this section sits, counting top-level sections as 1."""
        return 1 if self.parent is None else self.parent.depth + 1

    @property
    def number(self) -> str:
        """The derived section number, e.g. "3.1.2"."""
        if self.parent is None:
            return str(self.ordinal)
        return f"{self.parent.number}.{self.ordinal}"

    def markdown(
        self,
        image_prefix: str = "",
        bookmarks: dict[str, MarkdownSection] | None = None,
    ) -> str:
        """This section's own Markdown: its heading and content, not its children."""
        hashes = "#" * (self.depth + 1)
        lines = [f"{hashes} {self.number} {self.heading}", ""]

        content = self._resolved_content(image_prefix, bookmarks or {})
        if content:
            lines.extend((content, ""))

        return "\n".join(lines)

    def _resolved_content(
        self, image_prefix: str, bookmarks: dict[str, MarkdownSection]
    ) -> str:
        """Fill the template's holes: where the images live, and where a
        cross-reference points.

        Only a link target is rewritten, never prose. Image names are generated by
        the parser (`3.1_img_2.png`) so they cannot collide with anything the
        document itself says, and the `#` that makes an anchor an anchor is what
        keeps the two rewrites off each other's targets.

        A bookmark the document did not resolve to a section is left exactly as Word
        wrote it, as is every bookmark in a section rendered with no map at all.
        """
        content = self.content
        if image_prefix:
            for image in self.images:
                content = content.replace(
                    f"]({image.name})", f"]({image_prefix}{image.name})"
                )

        for name, section in bookmarks.items():
            content = content.replace(f"](#{name})", f"](#{section.number})")
        return content


@dataclass
class MarkdownDocument:
    """A parsed guidance document: a title and its sections in document order."""

    title: str = ""
    sections: list[MarkdownSection] = field(default_factory=list)
    bookmarks: dict[str, MarkdownSection] = field(default_factory=dict)

    @property
    def images(self) -> list[Image]:
        """Every image in the document, in section order."""
        return [image for section in self.sections for image in section.images]

    def markdown(self, image_prefix: str = "") -> str:
        """The whole document: its title followed by every section in order."""
        parts = [f"# {self.title}", ""]
        parts.extend(
            section.markdown(image_prefix, self.bookmarks) for section in self.sections
        )
        return "\n".join(parts)
